package com.interviewcoach.service.impl;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.interviewcoach.dto.response.RecommendationResponse;
import com.interviewcoach.entity.AnswerEvaluation;
import com.interviewcoach.entity.Recommendation;
import com.interviewcoach.entity.User;
import com.interviewcoach.enums.RecommendationType;
import com.interviewcoach.exception.ResourceNotFoundException;
import com.interviewcoach.repository.AnswerEvaluationRepository;
import com.interviewcoach.repository.InterviewAnswerRepository;
import com.interviewcoach.repository.RecommendationRepository;
import com.interviewcoach.repository.UserRepository;
import com.interviewcoach.service.RecommendationService;
import com.interviewcoach.util.SecurityUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class RecommendationServiceImpl implements RecommendationService {

    private final UserRepository userRepository;
    private final InterviewAnswerRepository interviewAnswerRepository;
    private final AnswerEvaluationRepository answerEvaluationRepository;
    private final RecommendationRepository recommendationRepository;
    private final ObjectMapper objectMapper;

    @Override
    @Transactional
    public List<RecommendationResponse> generateRecommendationsForCurrentUser() {
        User user = getCurrentUser();

        recommendationRepository.deleteByUserId(user.getId());

        List<AnswerEvaluation> evaluations = interviewAnswerRepository
                .findByInterviewQuestionInterviewSessionUserIdOrderByCreatedAtDesc(user.getId())
                .stream()
                .map(answer -> answerEvaluationRepository.findByInterviewAnswerId(answer.getId()).orElse(null))
                .filter(Objects::nonNull)
                .toList();

        if (evaluations.isEmpty()) {
            return Collections.emptyList();
        }

        List<Recommendation> generatedRecommendations = new ArrayList<>();

        Map<String, Long> weakTopicFrequency = new HashMap<>();

        for (AnswerEvaluation evaluation : evaluations) {
            List<String> missingPoints = readJsonArray(evaluation.getMissingPointsJson());
            List<String> weaknesses = readJsonArray(evaluation.getWeaknessesJson());

            for (String point : missingPoints) {
                weakTopicFrequency.put(point, weakTopicFrequency.getOrDefault(point, 0L) + 1);
            }

            for (String weakness : weaknesses) {
                weakTopicFrequency.put(weakness, weakTopicFrequency.getOrDefault(weakness, 0L) + 1);
            }

            if (evaluation.getTechnicalScore() < 60) {
                generatedRecommendations.add(
                        Recommendation.builder()
                                .user(user)
                                .type(RecommendationType.TOPIC)
                                .title("Improve technical depth")
                                .content("Revise core concepts behind the answers where your technical score was low. Focus on correctness, examples, and interviewer-style explanation.")
                                .build()
                );
            }

            if (evaluation.getCommunicationScore() < 60) {
                generatedRecommendations.add(
                        Recommendation.builder()
                                .user(user)
                                .type(RecommendationType.ACTION)
                                .title("Practice concise explanations")
                                .content("Your communication score is low in some answers. Practice giving structured answers using definition, explanation, example, and conclusion format.")
                                .build()
                );
            }

            if (evaluation.getOverallScore() < 60) {
                generatedRecommendations.add(
                        Recommendation.builder()
                                .user(user)
                                .type(RecommendationType.QUESTION)
                                .title("Retry weak interview questions")
                                .content("Reattempt the questions where your overall score was below 60 and compare your answer with the improved answer generated by the system.")
                                .build()
                );
            }
        }

        weakTopicFrequency.entrySet().stream()
                .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
                .limit(5)
                .forEach(entry -> generatedRecommendations.add(
                        Recommendation.builder()
                                .user(user)
                                .type(RecommendationType.TOPIC)
                                .title("Focus on: " + trimTitle(entry.getKey()))
                                .content("This topic appeared repeatedly in your weak areas. Study and practice it before your next mock interview: " + entry.getKey())
                                .build()
                ));

        List<Recommendation> uniqueRecommendations = deduplicateRecommendations(generatedRecommendations);
        List<Recommendation> saved = recommendationRepository.saveAll(uniqueRecommendations);

        return saved.stream()
                .map(this::mapToResponse)
                .toList();
    }

    @Override
    public List<RecommendationResponse> getMyRecommendations() {
        User user = getCurrentUser();

        return recommendationRepository.findByUserIdOrderByCreatedAtDesc(user.getId()).stream()
                .map(this::mapToResponse)
                .toList();
    }

    private User getCurrentUser() {
        String email = SecurityUtils.getCurrentUserEmail();
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));
    }

    private List<String> readJsonArray(String json) {
        try {
            return objectMapper.readValue(json, new TypeReference<List<String>>() {});
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to deserialize recommendation JSON", ex);
        }
    }

    private List<Recommendation> deduplicateRecommendations(List<Recommendation> recommendations) {
        Map<String, Recommendation> uniqueMap = new LinkedHashMap<>();

        for (Recommendation recommendation : recommendations) {
            String key = recommendation.getType() + "|" + recommendation.getTitle() + "|" + recommendation.getContent();
            uniqueMap.putIfAbsent(key, recommendation);
        }

        return new ArrayList<>(uniqueMap.values());
    }

    private String trimTitle(String input) {
        if (input == null || input.isBlank()) {
            return "Weak Topic";
        }
        return input.length() > 50 ? input.substring(0, 50) + "..." : input;
    }

    private RecommendationResponse mapToResponse(Recommendation recommendation) {
        return RecommendationResponse.builder()
                .id(recommendation.getId())
                .type(recommendation.getType())
                .title(recommendation.getTitle())
                .content(recommendation.getContent())
                .createdAt(recommendation.getCreatedAt())
                .build();
    }
}