spring.application.name=interview-coach-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/interview_coach_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080